name: lxi-tools
version: '1.12'
summary: Open source LXI tools
description: |
  Lxi-tools is a collection of open source software tools that enables control
  of LXI compatible instruments such as modern oscilloscopes, power supplies,
  spectrum analyzers etc.

grade: stable
confinement: strict
icon: gui/lxi-tools_256x256.png

apps:
  lxi:
    command: bin/lxi
    completer: share/bash-completion/completions/lxi
    plugs: [home, network, avahi-observe]
    aliases: [lxi]

parts:
  lxi-tools:
    plugin: autotools
    source: https://github.com/lxi/lxi-tools.git
    stage-packages: [libreadline-dev]
    after: [liblxi]
  liblxi:
    plugin: autotools
    source: https://github.com/lxi/liblxi.git
    stage-packages: [libavahi-core-dev, libavahi-common-dev, libavahi-client-dev]
