name: lxi-tools
summary: Open source LXI tools
description: >
  Lxi-tools are open source software tools for managing LXI compatible test
  instruments such as modern oscilloscopes, power supplies, spectrum analyzers
  etc.

  Features include automatic discovery of test instruments, sending SCPI
  commands, grabbing screenshots from supported instruments, benchmarking SCPI
  message performance, and powerful scripting for test automation. Both a
  commandline tool and a GUI application are available.

version: '2.3'
base: core22
grade: stable
confinement: strict

icon: snap/gui/lxi-tools_256x256.png

slots:
  dbus-slot-lxi-tools:
    interface: dbus
    bus: session
    name: io.github.lxi-tools

apps:
  lxi:
    command: usr/bin/lxi
    completer: usr/share/bash-completion/completions/lxi
    plugs:
      - avahi-control
      - home
      - network
  lxi-gui:
    command: usr/bin/lxi-gui
    plugs:
      - avahi-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - x11
      - wayland
    slots:
      - dbus-slot-lxi-tools
    environment:
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      XDG_DATA_DIRS: "$SNAP/usr/share:$XDG_DATA_DIRS"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache"
      GDK_PIXBUF_MODULE_FILE: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache"
      XKB_CONFIG_ROOT: "$SNAP/usr/share/X11/xkb"

build-packages:
  - pkg-config
  - cmake
  - gettext
  - appstream-util
  - desktop-file-utils
  - libglib2.0-bin
  - gtk-update-icon-cache
  - dbus
  - libxml2-utils

parts:

  liblxi:
    plugin: meson
    source: https://github.com/lxi-tools/liblxi.git
    source-depth: 1
    meson-parameters: [--prefix=/usr]
    build-packages:
      - libavahi-core-dev
      - libavahi-common-dev
      - libavahi-client-dev
      - libxml2-dev
      - libtirpc-dev
      - libicu-dev
      - meson
      - ninja-build
    stage-packages:
      - libavahi-core7
      - libavahi-common3
      - libavahi-client3
      - libxml2
      - libicu70

  lxi-tools:
    after: [liblxi]
    plugin: meson
    source: https://github.com/lxi-tools/lxi-tools.git
    source-tag: v2.3
    source-depth: 1
    meson-parameters: [--prefix=/usr,-Dgui=true,-Dgtksourceview:introspection=disabled]
    build-packages:
      - libreadline-dev
      - liblua5.4-dev
      - bash-completion
      - libgtk-4-dev
      - libgtksourceview-5-dev
      - meson
      - ninja-build
    stage-packages:
      - libreadline8
      - liblua5.4-0
      - bash-completion
      - libgtk-4-1
      - libgtksourceview-5-0
      - libegl1
      - libegl1-mesa
      - libgdk-pixbuf-2.0-0

  post-install-fixes:
    after: [lxi-tools]
    plugin: nil
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas
      gtk-update-icon-cache -qtf usr/share/icons/hicolor
      gtk-update-icon-cache -qtf usr/share/icons/Adwaita
      # gtk-update-icon-cache -qtf usr/share/icons/Yaru
      update-desktop-database -q usr/share/applications
      mkdir -p var/lib/dbus
      dbus-uuidgen > var/lib/dbus/machine-id
      ./usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache
      sed -i 's%/usr/lib/x86_64-linux-gnu%/snap/lxi-tools/current/usr/lib/x86_64-linux-gnu%g' usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache
