name: lxi-tools
summary: Open source LXI tools
description: >
  Lxi-tools are open source software tools for managing LXI compatible test
  instruments such as modern oscilloscopes, power supplies, spectrum analyzers
  etc.

  Features include automatic discovery of test instruments, sending SCPI
  commands, grabbing screenshots from supported instruments, benchmarking SCPI
  message performance, and powerful scripting for test automation. Both a
  commandline tool and a GUI application are available.

version: '2.1'
base: core20
grade: stable
confinement: strict

icon: snap/gui/lxi-tools_256x256.png

slots:
  dbus-slot-lxi-tools:
    interface: dbus
    bus: session
    name: io.github.lxi-tools

apps:
  lxi:
    command: usr/bin/lxi
    plugs:
      - avahi-control
      - home
      - network
  lxi-gui:
    command: usr/bin/lxi-gui
    plugs:
      - avahi-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - x11
      - wayland
    slots:
      - dbus-slot-lxi-tools
    environment:
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      XDG_DATA_DIRS: "$SNAP/usr/share:$XDG_DATA_DIRS"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache"

build-packages:
  - pkg-config
  - cmake
  - gettext
  - appstream-util
  - desktop-file-utils
  - libglib2.0-bin
  - gtk-update-icon-cache
  - dbus
  - libxml2-utils

parts:

  wayland-protocols:
    plugin: meson
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: "1.24"
    meson-parameters: [--prefix=/usr]

  patches:
    plugin: dump
    source: patches

  gtk:
    after: [wayland-protocols, patches]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/gtk.git
    source-commit: 92051931474a1fa41f723b3d41ab53c6cd410e79
    override-pull: |
      snapcraftctl pull
      patch -p1 -i $SNAPCRAFT_STAGE/gtk-disable-fast-resource-building.patch
    meson-parameters:
      - --prefix=/usr
      - -Ddemos=false
      - -Dbuild-tests=false
      - -Dbuild-examples=false
      - -Dgdk-pixbuf:builtin_loaders=all
    build-packages:
      - libglib2.0-dev
      - shared-mime-info
      - libxkbcommon-dev
      - libcairo2-dev
      - libxrandr-dev
      - libxi-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxinerama-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libharfbuzz-dev
      - libpango1.0-dev
      - libepoxy-dev
      - libgraphene-1.0-dev
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - libegl1-mesa-dev
      - libgl1-mesa-dri
      - libgbm-dev
      - libvulkan-dev
      - libwayland-dev
      - wayland-protocols
      - python3-gi
      - mesa-common-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libpixman-1-dev
      - libjpeg-turbo8-dev
      - libtiff-dev
      - libsass-dev
    stage-packages:
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgraphene-1.0-0
      - libgraphite2-3
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-bad1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgudev-1.0-0
      - libharfbuzz0b
      - libjbig0
      - libjpeg-turbo8
      - liborc-0.4-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libtiff5
      - libwebp6
      - gsettings-ubuntu-schemas
      - gsettings-desktop-schemas
      - xdg-user-dirs
      - adwaita-icon-theme
      - adwaita-icon-theme-full
      - yaru-theme-icon
      - libwayland-egl1-mesa
      - libwayland-egl1
      - libwayland-client0
      - libwayland-server0
      - libgbm1
      - libglu1-mesa
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libegl-mesa0
      - libegl1
      - libegl1-mesa
      - libglx-mesa0
      - libgles2-mesa
      - libglapi-mesa
      - libgl1
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxft2
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libsass1

  liblxi:
    plugin: meson
    source: https://github.com/lxi-tools/liblxi.git
    source-depth: 1
    meson-parameters: [--prefix=/usr]
    build-packages:
      - libavahi-core-dev
      - libavahi-common-dev
      - libavahi-client-dev
      - libxml2-dev
      - libtirpc-dev
    stage-packages:
      - libavahi-core7
      - libavahi-common3
      - libavahi-client3
      - libxml2
      - libicu66

  lxi-tools:
    after: [liblxi, gtk]
    plugin: meson
    source: https://github.com/lxi-tools/lxi-tools.git
    source-depth: 1
    meson-parameters: [--prefix=/usr,-Dgui=true,-Dgtksourceview:introspection=disabled]
    build-packages:
      - libreadline-dev
      - liblua5.3-dev
      - bash-completion
    stage-packages:
      - libreadline5
      - liblua5.3-0
      - bash-completion

  post-install-fixes:
    after: [lxi-tools]
    plugin: nil
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas
      gtk-update-icon-cache -qtf usr/share/icons/hicolor
      gtk-update-icon-cache -qtf usr/share/icons/Adwaita
      gtk-update-icon-cache -qtf usr/share/icons/Yaru
      update-desktop-database -q usr/share/applications
      mkdir -p var/lib/dbus
      dbus-uuidgen > var/lib/dbus/machine-id
