name: lxi-tools
summary: Open source LXI tools
description: >
  Lxi-tools are open source software tools for managing LXI compatible test
  instruments such as modern oscilloscopes, power supplies, spectrum analyzers
  etc.

  Features include automatic discovery of test instruments, sending SCPI
  commands, grabbing screenshots from supported instruments, benchmarking SCPI
  message performance, and powerful scripting for test automation. Both a
  commandline tool and a GUI application are available.

adopt-info: lxi-tools
base: core24
grade: stable
confinement: strict

icon: snap/gui/lxi-tools_256x256.png

slots:
  dbus-slot-lxi-tools:
    interface: dbus
    bus: session
    name: io.github.lxi-tools

apps:
  lxi:
    command: usr/bin/lxi
    completer: usr/share/bash-completion/completions/lxi
    plugs:
      - avahi-control
      - home
      - network
  lxi-gui:
    command: usr/bin/lxi-gui
    extensions: [gnome]
    plugs:
      - avahi-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - x11
      - wayland
    slots:
      - dbus-slot-lxi-tools
    environment:
      LC_ALL: C.UTF-8
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
      XDG_DATA_DIRS: "$SNAP/usr/share:$XDG_DATA_DIRS"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache"
      GDK_PIXBUF_MODULE_FILE: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache"
      XKB_CONFIG_ROOT: "$SNAP/usr/share/X11/xkb"
      LUA_PATH: "$SNAP/usr/share/lua/5.4/?.lua;$SNAP/usr/lib/lua/?.lua"
      LUA_CPATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lua/5.4/?.so"

build-packages:
  - pkg-config
  - cmake
  - gettext
  - appstream-util
  - desktop-file-utils
  - libglib2.0-bin
  - gtk-update-icon-cache
  - dbus
  - libxml2-utils

parts:

  liblxi:
    plugin: meson
    source: https://github.com/lxi-tools/liblxi.git
    source-depth: 1
    meson-parameters: [--prefix=/usr]
    build-packages:
      - libavahi-core-dev
      - libavahi-common-dev
      - libavahi-client-dev
      - libxml2-dev
      - libtirpc-dev
      - libicu-dev
      - meson
      - ninja-build
    stage-packages:
      - libavahi-core7
      - libavahi-common3
      - libavahi-client3
      - libxml2
      - libicu74

  lxi-tools:
    after: [liblxi]
    plugin: meson
    source: https://github.com/lxi-tools/lxi-tools.git
    source-depth: 0
    meson-parameters: [--prefix=/usr,-Dgui=true,-Dgtksourceview:introspection=disabled]
    build-packages:
      - libreadline-dev
      - liblua5.4-dev
      - bash-completion
      - meson
      - ninja-build
    stage-packages:
      - libreadline8
      - liblua5.4-0
      - bash-completion
      - libgdk-pixbuf-2.0-0
      - lua-socket
      - lua-cjson
    override-pull: |
       craftctl default
       craftctl set version=$(git describe --always --dirty | sed 's/^v//')

  post-install-fixes:
    after: [lxi-tools]
    plugin: nil
    override-prime: |
      set -eux
      craftctl default
      glib-compile-schemas usr/share/glib-2.0/schemas
      for dir in usr/share/icons/*; do
        if [ -f "$dir/index.theme" ]; then
          gtk-update-icon-cache --force "$dir"
        fi
      done
      update-desktop-database -q usr/share/applications
      mkdir -p var/lib/dbus
      dbus-uuidgen > var/lib/dbus/machine-id
      ./usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache
      sed -i 's%/usr/lib/x86_64-linux-gnu%/snap/lxi-tools/current/usr/lib/x86_64-linux-gnu%g' usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache

