name: lxi-tools
summary: Open source LXI tools
description: >
  Lxi-tools is a collection of open source software tools for managing LXI
  compatible instruments such as modern oscilloscopes, power supplies, spectrum
  analyzers etc.

version: '1.22'
icon: snap/gui/lxi-tools_256x256.png
base: core20
grade: devel
confinement: strict

apps:
  lxi:
    command: usr/bin/lxi
    completer: usr/share/bash-completion/completions/lxi.snap
    plugs: [home, network, avahi-observe]
    aliases: [lxi]
  lxi-gui:
    command: desktop-launch lxi-gui
    plugs: [home, network, avahi-observe, wayland, x11, opengl, removable-media]
    aliases: [lxi-gui]

parts:
  lxi-tools:
    plugin: meson
    source: https://github.com/lxi-tools/lxi-tools.git
    build: |
      meson build --prefix=/usr
      ninja -C build
    install: ninja -C build install
    build-packages:
      - pkg-config
      - libreadline-dev
      - liblua5.2-dev
      - libtirpc-dev
      - bash-completion
    stage-packages:
      - liblxi1
      - libreadline6
      - liblua5.2-0
      - bash-completion
    after: [liblxi]
  liblxi:
    plugin: autotools
    source: https://github.com/lxi-tools/liblxi.git
    build-packages: [pkg-config]
    stage-packages: [libavahi-core-dev, libavahi-common-dev, libavahi-client-dev, libxml2-dev]
    configflags: [--prefix=/usr]
