name: lxi-tools
version: '1.17'
summary: Open source LXI tools
description: |
  Lxi-tools is a collection of open source software tools that enables control
  of LXI compatible instruments such as modern oscilloscopes, power supplies,
  spectrum analyzers etc.

grade: stable
confinement: strict
icon: snap/icon/lxi-tools_256x256.png

apps:
  lxi:
    command: bin/lxi
    completer: share/bash-completion/completions/lxi
    plugs: [home, network, avahi-observe]
    aliases: [lxi]
  lxi-gui:
    command: desktop-launch lxi-gui
    plugs: [home, network, avahi-observe, desktop, desktop-legacy, x11, unity7, wayland]

parts:
  lxi-tools:
    plugin: autotools
    source: https://github.com/lxi-tools/lxi-tools.git
    build: |
      ./autogen.sh
      ./configure --prefix= --enable-lxi-gui
      make STAGE=$SNAPCRAFT_STAGE
    install: make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - pkg-config
      - qt5-default
      - qt5-qmake
      - qtbase5-dev
      - libreadline-dev
    stage-packages:
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libqt5dbus5
      - libqt5svg5
      - libreadline6
    after: [liblxi, desktop-qt5]
  liblxi:
    plugin: autotools
    source: https://github.com/lxi-tools/liblxi.git
    build-packages: [pkg-config]
    stage-packages: [libavahi-core-dev, libavahi-common-dev, libavahi-client-dev, libxml2-dev]
