name: lxi-tools
summary: Open source LXI tools
description: >
  Lxi-tools is a collection of open source software tools for managing LXI
  compatible instruments such as modern oscilloscopes, power supplies, spectrum
  analyzers etc.

version: '1.22'
icon: snap/gui/lxi-tools_256x256.png
base: core20
grade: devel
confinement: strict

apps:
  lxi:
    command: usr/bin/lxi
    completer: usr/share/bash-completion/completions/lxi.snap
    plugs: [home, network, avahi-observe]
      #  lxi-gui:
      #    command: lxi-gui
      #    plugs: [home, network, avahi-observe, wayland, x11, opengl, removable-media]

parts:
  lxi-tools:
    plugin: meson
    source: https://github.com/lxi-tools/lxi-tools.git
    meson-parameters: [--prefix=/usr]
    build-packages:
      - pkg-config
      - liblxi-dev
      - libreadline-dev
      - liblua5.2-dev
      - bash-completion
    stage-packages:
      - libreadline5
      - liblua5.2-0
      - bash-completion
    after: [liblxi]
  liblxi:
    plugin: meson
    source: https://github.com/lxi-tools/liblxi.git
    meson-parameters: [--prefix=/usr]
    build-packages:
      - pkg-config
      - libavahi-core-dev
      - libavahi-common-dev
      - libavahi-client-dev
      - libxml2-dev
      - libtirpc-dev
    stage-packages:
      - libavahi-core7
      - libavahi-common3
      - libavahi-client3
      - libxml2
      - libicu66
